import { pgTable, varchar, integer } from "drizzle-orm/pg-core";

export const clinics = pgTable("clinics", {
  longNameVersion: varchar("Long Name Version", { length: 200 }),
  typeformRegistrationLink: varchar("Typeform registration link", { length: 300 }),
  pms: varchar("pms", { length: 100 }),
  metaTitle: varchar("Meta-title", { length: 200 }),
  metaDescription: varchar("Meta-description", { length: 300 }),
  slug: varchar("slug", { length: 100 }),
  website: varchar("website", { length: 200 }),
  clinicName: varchar("Clinic Name", { length: 200 }),
  displayOnWeb: varchar("display_on_web", { length: 50 }),
  linkToClinicSuburbPage: varchar("link to clinic suburb page", { length: 200 }),
  fullAddress: varchar("Full Address", { length: 200 }),
  city: varchar("city", { length: 100 }),
  suburb: varchar("suburb", { length: 100 }),
  state: varchar("state", { length: 50 }),
  postcode: varchar("postcode", { length: 500 }),
  email: varchar("email", { length: 500 }),
  phone: varchar("phone", { length: 500 }),
  nearby1Txt: varchar("nearby1_txt", { length: 500 }),
  nearby1Link: varchar("nearby1_link", { length: 500 }),
  nearby2Txt: varchar("nearby2_txt", { length: 500 }),
  nearby2Link: varchar("nearby2_link", { length: 500 }),
  nearby3Txt: varchar("nearby3_txt", { length: 500 }),
  nearby3Link: varchar("nearby3_link", { length: 500 }),
  nearby4Txt: varchar("nearby4_txt", { length: 500 }),
  nearby4Link: varchar("nearby4_link", { length: 500 }),
  aboutClinic: varchar("About Clinic", { length: 1000 }),
});

export const suburbs = pgTable("suburbs", {
  column1: integer("column1"),
  suburbSlug: varchar("suburb-slug", { length: 100 }),
  suburbName: varchar("suburb_name", { length: 100 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 50 }),
  postcode: varchar("postcode", { length: 50 }),
  metaTitle: varchar("meta_title", { length: 500 }),
  metaDescription: varchar("meta_description", { length: 500 }),
  h1: varchar("h1", { length: 500 }),
  h2: varchar("h2", { length: 500 }),
  aboutBookphysio: varchar("about_bookphysio", { length: 1000 }),
  nearby1Link: varchar("nearby1_link", { length: 100 }),
  nearby1Txt: varchar("nearby1_txt", { length: 500 }),
  nearby1State: varchar("nearby1_state", { length: 50 }),
  nearby1Postcode: varchar("nearby1_postcode", { length: 50 }),
  nearby2Link: varchar("nearby2_link", { length: 100 }),
  nearby2Txt: varchar("nearby2_txt", { length: 500 }),
  nearby2State: varchar("nearby2_state", { length: 50 }),
  nearby2Postcode: varchar("nearby2_postcode", { length: 50 }),
  nearby3Link: varchar("nearby3_link", { length: 100 }),
  nearby3Txt: varchar("nearby3_txt", { length: 500 }),
  nearby3State: varchar("nearby3_state", { length: 50 }),
  nearby3Postcode: varchar("nearby3_postcode", { length: 50 }),
  nearby4Link: varchar("nearby4_link", { length: 100 }),
  nearby4Txt: varchar("nearby4_txt", { length: 500 }),
  nearby4State: varchar("nearby4_state", { length: 50 }),
  nearby4Postcode: varchar("nearby4_postcode", { length: 50 }),
});

export const cities = pgTable("cities", {
  citySlug: varchar("city_slug", { length: 50 }),
  cityName: varchar("city_name", { length: 50 }),
  state: varchar("state", { length: 50 }),
  metaTitle: varchar("meta_title", { length: 64 }),
  metaDescription: varchar("meta_description", { length: 256 }),
  h1: varchar("h1", { length: 50 }),
  h2: varchar("h2", { length: 64 }),
  subHeadingText: varchar("sub_heading_text", { length: 128 }),
  tick1: varchar("tick_1", { length: 50 }),
  tick2: varchar("tick_2", { length: 50 }),
  tick3: varchar("tick_3", { length: 50 }),
  aboutBookphysio: varchar("about_bookphysio", { length: 512 }),
});
